spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
server:
  port: 1178
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
